### ISSUE TITLE
Upload p8 file?

### ISSUE THREAD

**Issue by lyndsey-ferguson** [tkohout/fastlane-firebase-plugin#10]
I just found this plugin. Does this support adding a p8 file for an app (new or existing)? I don't see that.

**Comment by anh1979** [comment]
@felipe-augusto: Is this probably supported in your fork / version?
I added some log output to my local version to understand what is going on, but I would really like to see this feature added, because we have to add apps to firebase programmatically and adding a .p8 via this plugin would be so helpful and time-saving!

I am definitely not enough in to web scrapping yet that I could add this, I am sorry.

**Comment by felipe-augusto** [comment]
@anh1979 I will take a look at it, I think It's almost ready to go, but I do not have .p8 files to test. Could you test if it works for me?

**Comment by anh1979** [comment]
@felipe-augusto: Great! Of course I would like to test that - let me know, when you are ready (take your time, I'll be back in office next week).

If you have access to Apple Developer (paid account), you can generate an .p8 Key there, too if you want (in Certificates, Identifiers & Profiles > Keys, click the plus sign and choose APNs).

**Comment by lyndsey-ferguson** [comment]
I have a test dev account that I could use to help test this

**Comment by lyndsey-ferguson** [comment]
Oh, I'm ready to test this.

**Comment by lyndsey-ferguson** [comment]
Of course, there are the REST apis, but I do not see how they can be used to add the p8. Granted, I do not even see the REST endpoints that the `fastlane-plugin-firebase_management` uses in the docs either.

Could be that is something I to investigate further to understand
